Controller Atualizadas.
lucassdantas/ProjetoIntegrador pull request #155
Opened 2023-06-18 22:00 UTC by Lipee221

Controller atualizados para receber virgulas.

2023-06-18 22:26 UTC, lucassdantas requested changes

2023-06-18 22:26 UTC, lucassdantas commented on src/controllers/PortionCalcController.java
> -    private List<JTextField> calcItemFieldValue = new ArrayList<>();
Esse é o arquivo desatualizado. Pode baixar o que está atualizado e subir aqui, @luizfelipe02081 @Lipee221 ?

2023-06-19 03:21 UTC, JoaoVitorTRJ approved these changes

2023-06-19 03:29 UTC, lucassdantas approved these changes

2023-06-19 03:42 UTC, lucassdantas approved these changes

2023-06-19 03:43 UTC, merged